apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: goapp

images:
- name: goapp
  newName: viniciusfca/goapp
  newTag: 4721bc5bff2c51a38ce8aef580346c86fce52941
